apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: nodepool-worker
  namespace: hcp-demo
spec:
  arch: amd64
  clusterName: hcp-demo
  management:
    autoRepair: false
    replace:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      strategy: RollingUpdate
    upgradeType: InPlace
  platform:
    agent:
      agentLabelSelector:
        matchLabels:
          node-role.kubernetes.io/worker: ''
          worker: 'true'    
    type: Agent
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.18.9-x86_64
  replicas: 3
